enabled = true
debug = true
adapter = "sqlite"
[watch]
exchange = "bitfinex"
currency = "BTC"
asset = "LTC"
[watch]
exchange = "kraken"
currency = "XBT"
asset = "LTC"
[watch]
exchange = "poloniex"
currency = "BTC"
asset = "LTC"
[watch]
exchange = "exmo"
currency = "LTC"
asset = "ETH"
