enabled = true
debug = true
adapter = "sqlite"
[dependencies]
module="sqlite3"
[watch]
exchange = "bitfinex"
currency = "BTC"
asset = "LTC"
key=""
secret=""
[watch]
exchange = "kraken"
currency = "XBT"
asset = "LTC"
key=""
secret=""
[watch]
exchange = "poloniex"
currency = "BTC"
asset = "LTC"
key=""
secret=""
[watch]
exchange = "exmo"
currency = "LTC"
asset = "ETH"
key=""
secret=""
